### ISSUE TITLE
Crash on malformed query in `prolog` mode.

### ISSUE THREAD

**Issue by rotu** [guregu/trealla-js#39]
```
import { Prolog, load } from 'trealla';
await load()
const pl = new Prolog();
console.log(await Array.fromAsync(pl.query("true;", {format:"prolog"})))
```

This gives an error in WASM:
```
error: Uncaught (in promise) RuntimeError: memory access out of bounds
    at <anonymous> (wasm://wasm/00b8b4b6:1:47709)
    at <anonymous> (wasm://wasm/00b8b4b6:1:782535)
    at <anonymous> (wasm://wasm/00b8b4b6:1:753362)
    at Prolog.query (file:///Users/dan/Source/trealla-js/dist/trealla.js:3306:11)
    at query.next (<anonymous>)
```

It seems like there are two issues here:
1. WASM shouldn't exhaust its memory.
2. The generator should return instead of continuing after the exception.

JSON mode is much more reasonable, but gives a slightly different result than I was expecting - a syntax error for the `/` functor, which does not occur in my query.

```
[
  {
    status: "error",
    error: Compound {
      functor: "error",
      args: [
        Compound { functor: "syntax_error", args: [Array] },
        Compound { functor: "/", args: [Array] }
      ]
    }
  }
]
```

**Comment by guregu** [comment]
The JSON error makes more sense if you look at its entirety:
```
{
 "status": "error",
 "error": {
  "functor": "error",
  "args": [
   {
    "functor": "syntax_error",
    "args": [
     {
      "functor": "operand_missing",
      "args": []
     }
    ]
   },
   {
    "functor": "/",
    "args": [
     {
      "functor": "read_term_from_chars",
      "args": []
     },
     3
    ]
   }
  ]
 }
}
```

It looks like the prolog toplevel isn't stopping the iterator after it finds an error, shouldn't be too hard to fix.

**Comment by rotu** [comment]
> The JSON error makes more sense if you look at its entirety:

Translating to prolog syntax, I think that means:
`error(syntax_error('operand_missing'), read_term_from_chars/3)`

Wonder if there's a way to make that more intuitive...

**Comment by rotu** [comment]
> This is quite intuitive

Yes, it’s intuitive if you write it out in prolog syntax. It’s not intuitive that you have to dig into the return value to see `read_term_from_chars`.

**Comment by guregu** [comment]
You can call toString() to get it formatted nicely

**Comment by guregu** [comment]
Memory issue is fixed in the latest release: 0.24.13
It was trying to double-free the subquery iterator, now it will skip that if it errors out.

**Comment by rotu** [comment]
Awesome!
1. I can’t figure out what `toString` is expected to return - a simple representation, an unambiguous representation, or a prolog-syntax representation?
2. How do I build this locally? I’ve been downloading `tpl.wasm` from its release page because the build fails when I check out your fork of trealla and `npm build all`

**Comment by guregu** [comment]
toString() works like other JS types in that its main purpose is to aid in debugging (although "[object Object]" rarely helps me debug lol), so I don't really have a strong opinion on what it should be. Most of them just call toProlog() which gives you a syntax-valid Prolog representation as a string. Errors like this are just Prolog terms so you can call toProlog() on them and get something like that looks nice and is unambiguous.

Grab libtpl-js.wasm from the [releases page](https://github.com/guregu/trealla/releases), and rename it to libtpl.wasm in the root. There's a few JS specific things in there.

You need to install WASI-SDK, Binaryen, and Wizer to do the full build. Easiest way to deal with configuring your compiler is to set this env var https://github.com/guregu/trealla/blob/0c8fe21f491744f72271cf544cbe07a9078a4483/.github/workflows/build.yaml#L135
^ this workflow has the laziest method of setting things up for each OS, binaryen is on homebrew for example. I'll add a Github Action thingy here soonish too.

**Comment by guregu** [comment]
Also, you only need to run `npm run all` if you want to compile the wasm binary. Just `npm run build` is enough for making changes to the JS stuff if you already have the wasm binary.

**Comment by rotu** [comment]
Still experiencing this:

https://github.com/guregu/trealla/issues/24

But if it builds for you as-is I'll assume the problem is with the way I have my toolchain installed.

**Comment by guregu** [comment]
It looks like you're trying to build the wasm stuff with the non-wasi-sdk clang, maybe? It's a bit of a pain to setup

**Comment by guregu** [comment]
Anyway we can handle that in the other repo, sorry I missed that issue. It's annoying having to setup odd C compilers for sure.
